services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: centos-app
    restart: unless-stopped
    tty: true
    ports:
     - "80:80"
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/
      - PHP_DISPLAY_ERRORS=1
      - PHP_MEMORY_LIMIT=4096M
      - PHP_POST_MAX_SIZE=4096M
      - PHP_UPLOAD_MAX_FILESIZE=4096M
      - SERVICE_NGINX_CLIENT_MAX_BODY_SIZE=4096M
      - PHP_MAX_EXECUTION_TIME=-1
      - XDEBUG_MODE=off #off/debug
      - XDEBUG_START_WITH_REQUEST=yes
      - XDEBUG_CLIENT_PORT=9003
      - XDEBUG_CLIENT_HOST=host.docker.internal
      - XDEBUG_MAX_NESTING_LEVEL=1000
    working_dir: /var/www
    volumes:
      - ./:/var/www
      # - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf 

  #MySQL Service
  db:
    image: mariadb:10.2.44
    container_name: centos_db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    volumes:
      - dbdata:/var/lib/mysql/
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./:/var/www

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: centos_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASS}
      UPLOAD_LIMIT: 100M
    ports:
      - "8081:80"
    depends_on:
      - db

#Volumes
volumes:
  dbdata:
    driver: local
